import { createFileRoute } from "@tanstack/react-router";
import { BarChart3, Download, FileText, Plus } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { SectionCard } from "@/components/section-card";
import { Button } from "@/components/ui/button";
import { AreaTrendChart, BarSeriesChart } from "@/components/charts";
import { monthlyTrend, departmentProgress, challengeVsSolution } from "@/lib/mock-data";
import { useWorkspaceStore } from "@/hooks/use-workspace-store";
import { useState } from "react";
import { toast } from "sonner";

// Dialog components
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogClose,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

// DropdownMenu components
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

// Export imports
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Reports — PB39" },
      { name: "description", content: "Saved reports and exports for leadership reviews." },
    ],
  }),
  component: ReportsPage,
});

interface ReportItem {
  title: string;
  description: string;
  updated: string;
}

function ReportsPage() {
  const { reports, addReport, orgGoals, smartGoals, challenges } = useWorkspaceStore();

  const [dialogOpen, setDialogOpen] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newDesc, setNewDesc] = useState("");

  // Viewing report states
  const [viewOpen, setViewOpen] = useState(false);
  const [activeReport, setActiveReport] = useState<ReportItem | null>(null);

  const handleCreateReport = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle) return;

    addReport({
      title: newTitle,
      description: newDesc,
      updated: "Just now",
    });

    toast.success(`Report "${newTitle}" created!`);
    setNewTitle("");
    setNewDesc("");
    setDialogOpen(false);
  };

  const handleDownload = (r: ReportItem, format: "txt" | "excel" | "pdf") => {
    const filename = `${r.title.toLowerCase().replace(/\s+/g, "-")}-report`;

    if (format === "txt") {
      try {
        const fileContent = `REPORT SUMMARY: ${r.title.toUpperCase()}
Description: ${r.description}
Updated: ${r.updated}

==================================
LATEST PERFORMANCE METRICS
==================================
Total Strategic Objectives: ${orgGoals.length}
Total SMART Goals: ${smartGoals.length}
Active Challenges: ${challenges.filter(c => c.status !== "Resolved").length}

Goal Progress List:
${orgGoals.map((g) => `- ${g.name} (${g.progress}%) [Status: ${g.status}]`).join("\n")}

Generated by PB39 Personal Board Hub on ${new Date().toLocaleDateString()}.`;

        const blob = new Blob([fileContent], { type: "text/plain;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `${filename}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        toast.success(`Downloaded ${r.title} text summary!`);
      } catch (err) {
        toast.error("Failed to download text report.");
      }
    } else if (format === "excel") {
      try {
        const headers = ["Organization Goal", "Department", "Owner", "Progress", "Status"];
        const rows = orgGoals.map((g) => [
          g.name,
          g.department,
          g.owner,
          `${g.progress}%`,
          g.status,
        ]);

        const worksheet = XLSX.utils.aoa_to_sheet([
          [`Report Name: ${r.title}`],
          [`Description: ${r.description}`],
          [`Generated Date: ${new Date().toLocaleDateString()}`],
          [], // spacing
          headers,
          ...rows
        ]);

        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, "Report Metrics");

        // Set column widths
        worksheet["!cols"] = [
          { wch: 45 }, // goal name
          { wch: 18 }, // dept
          { wch: 15 }, // owner
          { wch: 12 }, // progress
          { wch: 15 }, // status
        ];

        XLSX.writeFile(workbook, `${filename}.xlsx`);
        toast.success(`Downloaded ${r.title} Excel spreadsheet!`);
      } catch (err) {
        toast.error("Failed to download Excel report.");
      }
    } else if (format === "pdf") {
      try {
        const doc = new jsPDF();

        // Title styling
        doc.setFont("helvetica", "bold");
        doc.setFontSize(16);
        doc.setTextColor(15, 23, 42); // slate-900
        doc.text(`Report: ${r.title}`, 14, 20);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(100, 116, 139); // slate-500
        doc.text(`Description: ${r.description}`, 14, 27, { maxWidth: 180 });
        doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 14, 38);

        // Line separator
        doc.setDrawColor(226, 232, 240); // border color slate-200
        doc.line(14, 42, 196, 42);

        // Core stats
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(15, 23, 42);
        doc.text("PERFORMANCE SUMMARY", 14, 50);

        const summaryStats = [
          ["Strategic Objectives", String(orgGoals.length), "Measurable SMART Targets", String(smartGoals.length)],
          ["Active Open Blockers", String(challenges.filter(c => c.status !== "Resolved").length), "Date Updated", r.updated]
        ];

        autoTable(doc, {
          startY: 54,
          head: [["Metric", "Value", "Metric", "Value"]],
          body: summaryStats,
          theme: "striped",
          headStyles: { fillColor: [79, 70, 229] }, // Indigo header
          styles: { fontSize: 8.5 },
          margin: { left: 14, right: 14 },
        });

        // Detail Goals list
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text("OBJECTIVE TRACKING BREAKDOWN", 14, (doc as any).lastAutoTable.finalY + 12);

        const tableHeaders = ["Strategic Objective", "Department", "Owner", "Progress", "Status"];
        const tableRows = orgGoals.map((g) => [
          g.name,
          g.department,
          g.owner,
          `${g.progress}%`,
          g.status
        ]);

        autoTable(doc, {
          startY: (doc as any).lastAutoTable.finalY + 16,
          head: [tableHeaders],
          body: tableRows,
          theme: "grid",
          headStyles: { fillColor: [15, 23, 42] }, // Slate-900
          styles: { fontSize: 8 },
          columnStyles: {
            0: { cellWidth: 85 },
          },
          margin: { left: 14, right: 14 },
        });

        doc.save(`${filename}.pdf`);
        toast.success(`Downloaded ${r.title} PDF report!`);
      } catch (err) {
        toast.error("Failed to download PDF report.");
      }
    }
  };

  const handleOpenReport = (r: ReportItem) => {
    setActiveReport(r);
    setViewOpen(true);
  };

  return (
    <div className="space-y-6 p-6 md:p-8">
      <PageHeader
        title="Reports"
        description="Pre-built and saved views for leadership and operating reviews."
        actions={
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button size="sm" className="cursor-pointer gap-1">
                <Plus className="h-3.5 w-3.5" />
                New report
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[420px]">
              <form onSubmit={handleCreateReport}>
                <DialogHeader>
                  <DialogTitle>Create Custom Report</DialogTitle>
                  <DialogDescription>
                    Establish a saved viewpoint of active workspace metrics.
                  </DialogDescription>
                </DialogHeader>

                <div className="grid gap-4 py-4">
                  <div className="space-y-1.5">
                    <Label htmlFor="rep-title">Report Title *</Label>
                    <Input
                      id="rep-title"
                      placeholder="e.g. LATAM Expansion Scorecard"
                      value={newTitle}
                      onChange={(e) => setNewTitle(e.target.value)}
                      required
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="rep-desc">Description</Label>
                    <Textarea
                      id="rep-desc"
                      placeholder="e.g. Monthly progress summary covering partner acquisitions..."
                      value={newDesc}
                      onChange={(e) => setNewDesc(e.target.value)}
                      rows={3}
                    />
                  </div>
                </div>

                <DialogFooter>
                  <DialogClose asChild>
                    <Button variant="outline" type="button" className="cursor-pointer">
                      Cancel
                    </Button>
                  </DialogClose>
                  <Button type="submit" className="cursor-pointer">Create Report</Button>
                </DialogFooter>
              </form>
            </DialogContent>
          </Dialog>
        }
      />

      <div className="grid gap-4 md:grid-cols-2">
        <SectionCard title="Goal achievement trend" description="Achieved vs target by month">
          <AreaTrendChart
            data={monthlyTrend}
            xKey="month"
            series={[
              { key: "achieved", label: "Achieved", color: "var(--color-chart-1)" },
              { key: "target", label: "Target", color: "var(--color-chart-2)" },
            ]}
          />
        </SectionCard>
        <SectionCard title="Department performance" description="Average progress by department">
          <BarSeriesChart
            data={departmentProgress}
            xKey="department"
            layout="vertical"
            series={[{ key: "progress", label: "Progress %", color: "var(--color-chart-1)" }]}
          />
        </SectionCard>
      </div>

      <SectionCard title="Challenges vs solutions" description="Issue flow across the organization">
        <BarSeriesChart
          data={challengeVsSolution}
          xKey="month"
          height={260}
          series={[
            { key: "challenges", label: "Challenges", color: "var(--color-chart-5)" },
            { key: "solutions", label: "Solutions", color: "var(--color-chart-3)" },
          ]}
        />
      </SectionCard>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {reports.map((r) => (
          <article key={r.title} className="flex flex-col rounded-xl border bg-card p-5 transition hover:shadow-sm">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
              <FileText className="h-4 w-4" />
            </div>
            <h3 className="mt-3 font-semibold leading-snug">{r.title}</h3>
            <p className="mt-1 text-xs text-muted-foreground line-clamp-2">{r.description}</p>
            <p className="mt-3 text-[11px] text-muted-foreground">Updated {r.updated}</p>
            <div className="mt-4 flex gap-2">
              <Button size="sm" variant="outline" className="flex-1 cursor-pointer" onClick={() => handleOpenReport(r)}>
                <BarChart3 className="mr-1.5 h-3.5 w-3.5" /> Open
              </Button>
              
              {/* Dropdown Menu for downloading report files */}
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button size="sm" variant="ghost" className="h-9 w-9 p-0 cursor-pointer">
                    <Download className="h-3.5 w-3.5" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-44">
                  <DropdownMenuItem onClick={() => handleDownload(r, "txt")} className="cursor-pointer">
                    Download Text (.txt)
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => handleDownload(r, "excel")} className="cursor-pointer">
                    Download Excel (.xlsx)
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => handleDownload(r, "pdf")} className="cursor-pointer">
                    Download PDF (.pdf)
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </article>
        ))}
      </div>

      {/* View Report Detail Dialog */}
      <Dialog open={viewOpen} onOpenChange={setViewOpen}>
        <DialogContent className="sm:max-w-[480px]">
          {activeReport && (
            <>
              <DialogHeader>
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary mb-2">
                  <FileText className="h-5 w-5" />
                </div>
                <DialogTitle className="text-left">{activeReport.title}</DialogTitle>
                <DialogDescription className="text-left">
                  {activeReport.description || "No description provided."}
                </DialogDescription>
              </DialogHeader>

              <div className="space-y-4 py-4 text-left">
                <div className="rounded-lg border bg-muted/20 p-4 space-y-2 text-xs">
                  <div className="flex justify-between font-semibold">
                    <span>Metrics Breakdown</span>
                    <span>Status</span>
                  </div>
                  <div className="border-t pt-2 space-y-1 text-muted-foreground">
                    <div className="flex justify-between">
                      <span>Total Strategic Objectives</span>
                      <span className="font-semibold text-foreground">{orgGoals.length}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Total SMART Goals</span>
                      <span className="font-semibold text-foreground">{smartGoals.length}</span>
                    </div>
                    <div className="flex justify-between">
                      <span>Active Blockers</span>
                      <span className="font-semibold text-destructive">{challenges.filter(c => c.status !== "Resolved").length}</span>
                    </div>
                  </div>
                </div>

                <div className="space-y-2">
                  <h4 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Objective Breakdown</h4>
                  <div className="max-h-40 overflow-y-auto space-y-1.5 pr-1">
                    {orgGoals.map((g) => (
                      <div key={g.id} className="flex items-center justify-between text-xs border rounded p-2">
                        <span className="font-medium truncate pr-4">{g.name}</span>
                        <span className="shrink-0 text-muted-foreground font-semibold">{g.progress}%</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <DialogFooter>
                <DialogClose asChild>
                  <Button variant="outline" size="sm" className="cursor-pointer">Close</Button>
                </DialogClose>
                
                {/* Modal actions download select formats dropdown */}
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button size="sm" className="cursor-pointer gap-1">
                      <Download className="h-3.5 w-3.5" /> Download Report
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-44">
                    <DropdownMenuItem onClick={() => handleDownload(activeReport, "txt")} className="cursor-pointer">
                      Download Text (.txt)
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleDownload(activeReport, "excel")} className="cursor-pointer">
                      Download Excel (.xlsx)
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => handleDownload(activeReport, "pdf")} className="cursor-pointer">
                      Download PDF (.pdf)
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
