/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SmartGoalsRouteImport } from './routes/smart-goals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OrganizationGoalsRouteImport } from './routes/organization-goals'
import { Route as EmotionalTrackingRouteImport } from './routes/emotional-tracking'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as ActionPlansRouteImport } from './routes/action-plans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'

const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartGoalsRoute = SmartGoalsRouteImport.update({
  id: '/smart-goals',
  path: '/smart-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationGoalsRoute = OrganizationGoalsRouteImport.update({
  id: '/organization-goals',
  path: '/organization-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionalTrackingRoute = EmotionalTrackingRouteImport.update({
  id: '/emotional-tracking',
  path: '/emotional-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlansRoute = ActionPlansRouteImport.update({
  id: '/action-plans',
  path: '/action-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/goals/$goalId',
  path: '/goals/$goalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-plans': typeof ActionPlansRoute
  '/challenges': typeof ChallengesRoute
  '/emotional-tracking': typeof EmotionalTrackingRoute
  '/organization-goals': typeof OrganizationGoalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/smart-goals': typeof SmartGoalsRoute
  '/solutions': typeof SolutionsRoute
  '/traceability': typeof TraceabilityRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-plans': typeof ActionPlansRoute
  '/challenges': typeof ChallengesRoute
  '/emotional-tracking': typeof EmotionalTrackingRoute
  '/organization-goals': typeof OrganizationGoalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/smart-goals': typeof SmartGoalsRoute
  '/solutions': typeof SolutionsRoute
  '/traceability': typeof TraceabilityRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-plans': typeof ActionPlansRoute
  '/challenges': typeof ChallengesRoute
  '/emotional-tracking': typeof EmotionalTrackingRoute
  '/organization-goals': typeof OrganizationGoalsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/smart-goals': typeof SmartGoalsRoute
  '/solutions': typeof SolutionsRoute
  '/traceability': typeof TraceabilityRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-plans'
    | '/challenges'
    | '/emotional-tracking'
    | '/organization-goals'
    | '/reports'
    | '/settings'
    | '/smart-goals'
    | '/solutions'
    | '/traceability'
    | '/goals/$goalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-plans'
    | '/challenges'
    | '/emotional-tracking'
    | '/organization-goals'
    | '/reports'
    | '/settings'
    | '/smart-goals'
    | '/solutions'
    | '/traceability'
    | '/goals/$goalId'
  id:
    | '__root__'
    | '/'
    | '/action-plans'
    | '/challenges'
    | '/emotional-tracking'
    | '/organization-goals'
    | '/reports'
    | '/settings'
    | '/smart-goals'
    | '/solutions'
    | '/traceability'
    | '/goals/$goalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionPlansRoute: typeof ActionPlansRoute
  ChallengesRoute: typeof ChallengesRoute
  EmotionalTrackingRoute: typeof EmotionalTrackingRoute
  OrganizationGoalsRoute: typeof OrganizationGoalsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SmartGoalsRoute: typeof SmartGoalsRoute
  SolutionsRoute: typeof SolutionsRoute
  TraceabilityRoute: typeof TraceabilityRoute
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-goals': {
      id: '/smart-goals'
      path: '/smart-goals'
      fullPath: '/smart-goals'
      preLoaderRoute: typeof SmartGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization-goals': {
      id: '/organization-goals'
      path: '/organization-goals'
      fullPath: '/organization-goals'
      preLoaderRoute: typeof OrganizationGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotional-tracking': {
      id: '/emotional-tracking'
      path: '/emotional-tracking'
      fullPath: '/emotional-tracking'
      preLoaderRoute: typeof EmotionalTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plans': {
      id: '/action-plans'
      path: '/action-plans'
      fullPath: '/action-plans'
      preLoaderRoute: typeof ActionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/goals/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionPlansRoute: ActionPlansRoute,
  ChallengesRoute: ChallengesRoute,
  EmotionalTrackingRoute: EmotionalTrackingRoute,
  OrganizationGoalsRoute: OrganizationGoalsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SmartGoalsRoute: SmartGoalsRoute,
  SolutionsRoute: SolutionsRoute,
  TraceabilityRoute: TraceabilityRoute,
  GoalsGoalIdRoute: GoalsGoalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
